services:

  server:
    container_name: server
    restart: always
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      - nats
    environment:
      - NATS_URL=nats://nats:4222

    command: [./chatroom]

  nats:
    image: nats:2.10-linux
    container_name: nats-server
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    environment:
      - NATS_SERVER_NAME=nats-chatroom
    command: >
      -DV 
   