services:
  nats:
    image: nats:2.10-linux
    container_name: nats-server
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    environment:
      - NATS_SERVER_NAME=nats-chatroom
    command: >
      -DV 